resources:
- repo: self

stages:
- stage: Validate
  jobs:
  - job: Validate
    continueOnError: false
    steps:
    - publish: terraform-plans
      artifact: terraform_out
    - task: TerraformInstaller@0
      displayName: 'Use Terraform v0.12.10'
      inputs:
        terraformVersion: 0.12.10
    - task: TerraformTaskV1@0
      displayName: 'terraform init'
      inputs:
        command: init
        workingDirectory: terraform-plans
        backendType: azurerm
        backendServiceArm: 'Biner Azure Cloud'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'gitopszootfstorage'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'gitopszoo.terraform.tfstate'
    - task: TerraformTaskV1@0
      displayName: 'terraform validate'
      inputs:
        command: validate
        workingDirectory: terraform-plans
 

- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: Deploy_Terraform
    pool:
      vmImage: 'ubuntu-latest'
    # creates an environment if it doesn’t exist
    environment: 'DEV'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          # - download: current
          #   artifact: terraform_out
          - task: TerraformTaskV1@0
            displayName: 'terraform init'
            inputs:
              command: init
              workingDirectory: $(Pipeline.Workspace)/terraform_out
              backendType: azurerm
              backendServiceArm: 'Biner Azure Cloud'
              backendAzureRmResourceGroupName: 'terraform-rg'
              backendAzureRmStorageAccountName: 'gitopszootfstorage'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'gitopszoo.terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: 'terraform plan'
            inputs:
              command: plan
              workingDirectory: $(Pipeline.Workspace)/terraform_out
              environmentServiceName: 'Biner Azure Cloud'
              secureVarsFile: 'aks_conf.tfvars'
              commandOptions: '-out $(Pipeline.Workspace)/terraform_out/terraform_gitopszoo_out'
              terraformVersion: 0.12.10
          - task: TerraformTaskV1@0
            displayName: 'terraform apply'
            inputs:
              command: apply
              workingDirectory: $(Pipeline.Workspace)/terraform_out
              environmentServiceName: 'Biner Azure Cloud'
              commandOptions: '$(Pipeline.Workspace)/terraform_out/terraform_gitopszoo_out'
              terraformVersion: 0.12.10